spring:
    jackson:
        serialization:
            indent_output: false
    datasource:
        ga:
            jdbc-url: jdbc:mysql://localhost:3306/ga?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver
        #  电信CRM客经系统数据库
        crm:
            jdbc-url: jdbc:mysql://localhost:3306/crm?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver
        # 电信大数据平台数据库，用于读取脱敏前数据
        dataplatform:
            jdbc-url: jdbc:mysql://localhost:3306/userlogdtl?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver
        # 电信大数据平台数据库，用于写入脱敏后数据
        userlog:
            jdbc-url: jdbc:mysql://localhost:3306/userlog1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver

        jmtlogstock:
            jdbc-url: jdbc:mysql://localhost:3306/jmt_log_stock?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            jadira:
                usertype:
                    autoRegisterUserTypes: true
        show-sql: true

    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB

    thymeleaf:
        cache: false
        encoding: UTF-8
        servlet:
            content-type: text/html

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
    reasonable: true
    page-size-zero: true
    support-methods-arguments: true

server:
    port: 8352

logging:
    file:
        path: ./log
    level:
        org:
            hibernate: WARN
            hibernate.SQL: WARN
#        com.lu.gademo.mapper: DEBUG

effectEva:
#    address: 192.168.37.192
    address: 127.0.0.1
    port: 10005
evidence:
#    localAddress: 172.28.72.214
    localAddress: 127.0.0.1
    localPort: 50004
#    remoteAddress: 172.28.72.214
    remoteAddress: 127.0.0.1
    remotePort: 50005
ruleCheck:
#    address: 172.28.72.224
    address: 127.0.0.1
    port: 30002
splitReconstruct:
#    address: 172.28.72.225
    address: 127.0.0.1
    port: 40011

evidenceSystem:
    evidenceReceipt:
        mainCommand: '0x0001'
        msgVersion: '0x1000'
        subCommand: '0x0020'
    evidenceRequest:
        mainCommand: '0x0001'
        msgVersion: '0x1000'
        subCommand: '0x0020'
    evidenceResponse:
        mainCommand: '0x0001'
        msgVersion: '0x1000'
        subCommand: '0x0020'
    submitEvidence:
        mainCommand: '0x0003'
        msgVersion: '0x3110'
        subCommand: '0x0031'

systemId:
    desenToolsetSystemId: '0x31000000'
    evaluationSystemId: '0x32000000'
    evidenceSystemId: '0x10000000'
    ruleCheckSystemId: '0x33000000'

logSenderManager:
    ifSendToEvaFirst: false
    ifSaveToDatabase: false
    ifSendFile: false
    ifPerformenceTest: false

pythonMock:
    evaSendFile: false
    splitSendFile: false

fetch:
    database:
        dataPlatformTask:
            enabled: false
            initialDelay: 5000   # 初始延迟时间（毫秒）
            fixedRate: 180000    # 间隔时间（毫秒）
            remoteConfigPath: /root/env_fenjifenlei/dataplatform_config.json
        jdPlatformTask:
            enabled: false
            initialDelay: 5000   # 初始延迟时间（毫秒）
            fixedRate: 180000    # 间隔时间（毫秒）
            jdTableName: t_user_info
            jdTargetTableName: t_user_info_desen
            ifSendToEvaluationSystem: true
            configFileName: jd_config
            remoteConfigPath: /root/env_fenjifenlei/jd_config.json
        pageSize:
            jdDatabase: 50000
course2:
    host: 127.0.0.1
    username: root
    password: GDS&123softswitch
    port: 9090
