spring:
    jackson:
        serialization:
            indent_output: false
    datasource:
        ga:
            jdbc-url: jdbc:mysql://localhost:3306/ga?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver

        crm:
            jdbc-url: jdbc:mysql://localhost:3306/crm?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver

        dataplatform:
            jdbc-url: jdbc:mysql://localhost:3306/userlogdtl?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver

        userlog:
            jdbc-url: jdbc:mysql://localhost:3306/userlog1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver

        jmtlogstock:
            jdbc-url: jdbc:mysql://10.30.0.102:3306/jmt_log_stock?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            password: BRysj0725HhRhL##
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            jadira:
                usertype:
                    autoRegisterUserTypes: true
        show-sql: true

    servlet:
        multipart:
            maxFileSize: 100MB
            maxRequestSize: 100MB

    thymeleaf:
        cache: false
        encoding: UTF-8
        servlet:
            content-type: text/html

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
    reasonable: true
    page-size-zero: true
    support-methods-arguments: true

server:
    port: 8352

logging:
    file:
        path: ./log
    level:
        org:
            hibernate: WARN
            hibernate.SQL: WARN

effectEva:
    address: 10.30.0.137
    port: 10005
evidence:
    localAddress: 10.30.0.11
    localPort: 50004
    remoteAddress: 10.30.0.11
    remotePort: 50005
ruleCheck:
    address: 10.30.0.3
    port: 30002
splitReconstruct:
    address: 10.30.0.5
    port: 40011

evidenceSystem:
    evidenceReceipt:
        mainCommand: '0x0001'
        msgVersion: '0x1000'
        subCommand: '0x0020'
    evidenceRequest:
        mainCommand: '0x0001'
        msgVersion: '0x1000'
        subCommand: '0x0020'
    evidenceResponse:
        mainCommand: '0x0001'
        msgVersion: '0x1000'
        subCommand: '0x0020'
    submitEvidence:
        mainCommand: '0x0003'
        msgVersion: '0x3110'
        subCommand: '0x0031'

systemId:
    desenToolsetSystemId: '0x31000000'
    evaluationSystemId: '0x32000000'
    evidenceSystemId: '0x10000000'
    ruleCheckSystemId: '0x33000000'

logSenderManager:
    ifSendToEvaFirst: true
    ifSaveToDatabase: true
    ifSendFile: true
    ifPerformenceTest: false

fetch:
    database:
        dataPlatformTask:
            enabled: false
            initialDelay: 5000   # 初始延迟时间（毫秒）
            fixedRate: 180000    # 间隔时间（毫秒）
            remoteConfigPath: /root/env_fenjifenlei/dataplatform_config.json
        jdPlatformTask:
            enabled: true
            initialDelay: 5000   # 初始延迟时间（毫秒）
            fixedRate: 180000    # 间隔时间（毫秒）
            jdTableName: t_user_info
            jdTargetTableName: t_user_info_desen
            ifSendToEvaluationSystem: false
            configFileName: jd_config
            remoteConfigPath: /root/env_fenjifenlei/jd_config.json
        pageSize:
            jdDatabase: 50000
course2:
    host: 127.0.0.1
    username: root
    password: GDS&123softswitch
    port: 9090